obj-$(CONFIG_SND_SUNXI_SOC_AUDIOCODEC) += sunxi_codec.o
obj-$(CONFIG_SND_SUNXI_SOC_AUDIOCODEC) += sunxi_codecdma.o
obj-$(CONFIG_SND_SUN8IW1_SNDCODEC) += sun8iw1_sndcodec.o
obj-$(CONFIG_SND_SUN8IW3_SNDCODEC) += sun8iw3_sndcodec.o
obj-$(CONFIG_SND_SUN8IW5_SNDCODEC) += sun8iw5_sndcodec.o
obj-$(CONFIG_SND_SUNXI_SOC_AUDIOCODEC) += sunxi_sndcodec.o
obj-$(CONFIG_SND_SUNXI_SWITCH) += switch_hdset.o


